### ISSUE TITLE
BDD netpublic (équipe Sonum)

### ISSUE THREAD

**Issue by JulienParis** [co-demos/carto-sonum#1]

**Comment by MEDNUM** [comment]
@JulienParis Pôle Emploi a une BDD en open data de ses agences. 
@BerengereAujard  Est-ce que ce ne serait pas aussi intéressant de les indiquer dans la mesure où y sont toujours disponibles 
- Un équipement
- Un accompagnement par un service civique sur les démarches Pôles emploi
