### ISSUE TITLE
éléments graphiques Sonum :

### ISSUE THREAD

**Issue by JulienParis** [co-demos/carto-sonum#12]
- [x] logos
- [x] typos
- [x] charte graphique

**Comment by JulienParis** [comment]
@lauriechap @BerengereAujard 
A terme on aura certainement besoin des logos et illustrations au format .png ou .jpg

**Comment by lauriechap** [comment]
@JulienParis À terme ? Peux-tu préciser ? Je t'exporterai au bons formats ceux intégrer dans les maquettes.

**Comment by JulienParis** [comment]
par "à terme" je voulais juste dire que pour le site livré (sans doute à partir du début de sprint#2) on aura besoin des exports des différents éléments (logos et illustrations), mais que dans l'immédiat ya pas urgence

**Comment by lauriechap** [comment]
Ok c'est noté. Oui attendons que les éléments soient fixés :)
