### ISSUE TITLE
premier modèle de données (équipe Sonum) : proposition pour les champs de la cartographie

### ISSUE THREAD

**Issue by JulienParis** [co-demos/carto-sonum#17]

**Comment by JulienParis** [comment]
première proposition : https://docs.google.com/document/d/1Jcw2XGKzF0U7zmmBQFg-bqaTFTx-aGUxN_a3Jsq6Tfk/edit

**Comment by JulienParis** [comment]
voir aussi : https://drive.google.com/drive/folders/1Rm49ARTyvEzCB9Vf6nPMHUsQBa-bRAni

**Comment by MEDNUM** [comment]
Bonjour j'ai produit un modèle de données sur la base 
- Des entretiens menés 
- Des champs existants
Ce sont les deux derniers onglets de cet excel : https://docs.google.com/spreadsheets/d/1agVnXuDet3PNM93ywwFlwPXKL-WNGmC5u_lMrigg3o8/edit?usp=sharing

Le premier onglet, champ new BDD complet reprend un modèle de données idéal
Le deuxième, champ new BDD MVP croise cet idéal avec la réalité des champs existants. C'est donc plutôt sur celui là qu'il conviendra de s'appuyer @JulienParis

**Comment by MEDNUM** [comment]
Bonjour j'ai produit un modèle de données sur la base 
- Des entretiens menés 
- Des champs existants
Ce sont les deux derniers onglets de cet excel : https://docs.google.com/spreadsheets/d/1agVnXuDet3PNM93ywwFlwPXKL-WNGmC5u_lMrigg3o8/edit?usp=sharing

Le premier onglet, champ new BDD complet reprend un modèle de données idéal
Le deuxième, champ new BDD MVP croise cet idéal avec la réalité des champs existants. C'est donc plutôt sur celui là qu'il conviendra de s'appuyer @JulienParis

**Comment by JulienParis** [comment]
vérifier cohérence [modèle](https://docs.google.com/spreadsheets/d/1agVnXuDet3PNM93ywwFlwPXKL-WNGmC5u_lMrigg3o8/edit#gid=1406968477)-[maquette](https://www.figma.com/proto/ZpwFxIAo4LqDnD5pn6PZjLjd/SoNum?node-id=9%3A17201&scaling=min-zoom&redirected=1)
