### ISSUE TITLE
Déterminer les fonctionnalités suivant les retours des entretiens

### ISSUE THREAD

**Issue by lauriechap** [co-demos/carto-sonum#24]

**Comment by JulienParis** [comment]
voir aussi : https://drive.google.com/drive/folders/1Rm49ARTyvEzCB9Vf6nPMHUsQBa-bRAni

**Comment by JulienParis** [comment]
et : https://docs.google.com/document/d/1NoeFdBhfC2zh3RzeqFo4wpBkg7H_zLtQiGxBh8kYZxg/edit

**Comment by JulienParis** [comment]
@MEDNUM pe changer cette carte de colonne en fonction de son niveau d'avancement + indiquer ici les liens vers la/les synthèse(s) : 
- lien/fichier de synthèse des fonctionnalités attendus
- lien/fichier de synthèse des entretiens

**Comment by JulienParis** [comment]
attente décision arbitrage scénario sortie site Sonum ? @FannyBeggiato @BerengereAujard
