### ISSUE TITLE
domain name pour prod / preprod

### ISSUE THREAD

**Issue by JulienParis** [co-demos/carto-sonum#6]

**Comment by JulienParis** [comment]
@FannyBeggiato @BerengereAujard

**Comment by JulienParis** [comment]
J'ai avancé cette carte afin qu'on puisse commencer à réserver un nom de domaine et un serveur

**Comment by FannyBeggiato** [comment]
Pour le nom de domaine, nous proposons : **carto.societenumerique.gouv.fr**
qui reprend les modèles de nom des autres sites de la Mission

**Comment by JulienParis** [comment]
Du coup si c’est en ´.gouv.fr’ il faudra voir avec votre dsi comment bien configurer les dns

**Comment by JulienParis** [comment]
mise en contact avec DSI Sonum ? @FannyBeggiato @BerengereAujard
